### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Transistors_OldSowjetAera.pretty#2]
I know virtually nothing about Soviet-specific electronics, but it appears this library is for SU/USSR transistor footprints. I Googled, but I don't find any datasheets. Info:
- https://en.wikipedia.org/wiki/Soviet_integrated_circuit_designation
- http://www.wylie.org.uk/technology/semics/Soviets/Soviets.htm
- http://www.weisd.com/store2/NTE102A.pdf (6.09mm dia vs 5.6mm; leads on 1.82mm dia vs 1.4mm)
- http://www.weisd.com/store2/NTE160.pdf (OK in body dia but doesn't give lead dia)
- http://nvlpubs.nist.gov/nistpubs/Legacy/TN/nbstechnicalnote265.pdf (many are close but none match)
- http://nvlpubs.nist.gov/nistpubs/Legacy/TN/nbstechnicalnote715.pdf (same as above)
- http://www.radiomuseum.org/tubes/tube_p13~2.html
- http://www.radiomuseum.org/tubes/tube_gc116.html
- https://alltransistors.com/pdfview.php?doc=p401_p402_p403a.pdf&dire=_russia (doesn't match)

I then tried Yandex to see if I could get any hits for seemingly valid Russian text (according to Google Translate) like П104  транзистор. I did find some stuff, but nothing that matched those footprints:
- http://x-shoker.ru/_fr/4/3383586.pdf
- http://lib.chipdip.ru/031/doc001031162.pdf

So... I dug fairly deep and I didn't find anything. That being said, I'm not familiar with the topic or the lingua franca of the SU/USSR semiconductor companies.

Unless we can get good data for these footprints, can this library be deprecated? The footprints aren't KLC compliant and they don't have descriptions that are helpful for finding a package that could be used to update the footprints. At the very least, this repo should be renamed since the current one is... poor.

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr

**Comment by SchrodingersGat** [comment]
I'm on board, I see no reason to keep these.

**Comment by evanshultz** [comment]
@SchrodingersGat Great. See https://github.com/KiCad/Transistors_OldSowjetAera.pretty/pull/3. Also, would you mind removing it from fp-lib-table?

**Comment by SchrodingersGat** [comment]
Yup, this has now been done. Thanks :)
